CREATE TABLE WEATHER_MEASUREMENT(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TEMPERATURE DECIMAL(6,2) NOT NULL,
  HUMIDITY DECIMAL(6,2) NOT NULL,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ( ID )
);
